[tools]
bun = "1.2.19"

[env]
_.path = "node_modules/.bin"
_.file = ".env"

[hooks]
postinstall = "bun install"

[tasks.build]
run = "tsc"
description = "Build JavaScript modules and TypeScript declarations"

[tasks."build:clean"]
run = "rm -rf dist"
description = "Clean build artifacts"

[tasks.type-check]
run = "tsc --noEmit"
description = "Type check the project"

[tasks.dev]
run = "bun run src/index.ts"
description = "Run development server"

[tasks.test]
depends = ["build"]
run = "vitest run"
description = "Build and run all tests"

[tasks."test:watch"]
depends = ["build"]
run = "vitest"
description = "Run tests in watch mode"

[tasks."test:bun"]
run = "bun test"
description = "Run bun tests (when working)"


[tasks.prepublishOnly]
run = "build"
description = "Prepare for publishing"

[tasks.fmt]
run = "biome check --write --unsafe ."
description = "Format and fix code with Biome"

[tasks.example]
run = "bun run dev"
dir = "example"
depends = ["install:example"]
description = "Run the Cloudflare D1 example application"

[tasks."install:example"]
run = "bun install"
dir = "example"
description = "Install dependencies for the example application"
